### ISSUE TITLE
06_ch4-3Road.ipynb: Sentinel-2 衛星データの取得ができない

### ISSUE THREAD

**Issue by takacharu** [tamanome/satelliteBook#10]
「Python で学ぶ衛星データ解析基礎」大変、楽しく読ませていただいています。

Google colab 環境で、python notebook ファイルを実行していますが、06_ch4-3Road.ipynb について質問がございます。以下の Sentinel-2 衛星のデータを pystac で search する所でエラーがでます。実は 2-3週間前に、他の章の python notebook で、同様に pystac で Sentinel-2 衛星を search する個所があり、その時はうまく動いたように記憶しています (以前に実行してうまくいったと思っている seach 部分を今、実行すると同様の所で怒られます)。何か、データサーバー側での query の仕方などに大きな変更があったのでしょうか。ご確認いただけますと幸いです。

`# 対象値周辺の緯度経度をbbox内へ
bbox = selSquare(109.945, 1.524, 109.973,1.548) # (min lon, min lat, max lon, max lat)
dates ='2020-09-01/2020-09-20'

api_url = 'https://earth-search.aws.element84.com/v0'
collection = "sentinel-s2-l2a-cogs"  # Sentinel-2, Level 2A (BOA)
s2STAC = Client.open(api_url, headers=[])

s2Search = s2STAC.search (
   intersects = bbox,
   datetime = dates,
  #  query = {"eo:cloud_cover": {"lt": 10}, "sentinel:valid_cloud_cover": {"eq": True}},
   collections = collection)

s2_items = [i.to_dict() for i in s2Search.get_items()]
print(f"{len(s2_items)} のシーンを取得")

items = s2Search.get_all_items()
df = gpd.GeoDataFrame.from_features(items.to_dict(), crs="epsg:4326")
# 雲量で並び替え
s2Gdf = df.sort_values('eo:cloud_cover').reset_index(drop=True)
s2Gdf.head()`

`---------------------------------------------------------------------------
DoesNotConformTo                          Traceback (most recent call last)
[<ipython-input-6-9ebcbe5a8e2c>](https://localhost:8080/#) in <cell line: 9>()
      7 s2STAC = Client.open(api_url, headers=[])
      8 
----> 9 s2Search = s2STAC.search (
     10    intersects = bbox,
     11    datetime = dates,

[/usr/local/lib/python3.10/dist-packages/pystac_client/client.py](https://localhost:8080/#) in search(self, method, max_items, limit, ids, collections, bbox, intersects, datetime, query, filter, filter_lang, sortby, fields)
    586 
    587         if not self.conforms_to(ConformanceClasses.ITEM_SEARCH):
--> 588             raise DoesNotConformTo(
    589                 "ITEM_SEARCH", "There is not fallback option available for search."
    590             )

DoesNotConformTo: Server does not conform to ITEM_SEARCH, There is not fallback option available for search.`

**Comment by tamanome** [comment]
エラー箇所のご指摘いただきありがとうございます！
確認して修正いたしますので、しばらくお待ちください。

**Comment by tamanome** [comment]
問題箇所を修正しました。
修正版のノートブックをご利用ください。

**Comment by takacharu** [comment]
ありがとうございます。問題なく動くことを確認いたしました。迅速な対応ありがとうございました。
