### ISSUE TITLE
01_ch3-1DataAccess.ipynbでのエラー

### ISSUE THREAD

**Issue by sukesuke3** [tamanome/satelliteBook#11]
購読者になります。
google colab上で実行しているのですが、下記の部分で実行エラーが出てしまいます。
原因が分からず、ご助言いただいてもよろしいでしょうか。

```python
gdal.Translate(imgJpg, imgTif, format='JPEG', scaleParams=[[0,3000,0,255]])
# scaleParamsの部分は空白[[]]でも動作します。その場合は、gdal.Translateが自動で最適なコントラストに設定しますが、多くの場合手動でやるほうが良い結果になります
im = Image.open('Masked_' +str(object_name) +'.jpg')
im

## やや長いですが、下記方法でも変換可能です（より厳密な定義）
# scale = '-scale 0 3000 0 255' # 画像の色調整を行います(16bitから8bit範囲へ変換)
# options_list = [
#     '-ot Byte', # 8bitまで扱う
#     '-of JPEG', # 変換後の画像フォーマット
#     scale # 画像のコントラスト
# ] 
# options_string = " ".join(options_list)

# gdal.Translate(imgJpg, # 変換後の画像（パスごと記入）
#                imgTif, # 変換元の画像
#                options=options_string) # オプション指定
```
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
[<ipython-input-33-bfe30adcdaa4>](https://localhost:8080/#) in <cell line: 3>()
      1 gdal.Translate(imgJpg, imgTif, format='JPEG', scaleParams=[[0,3000,0,255]])
      2 # scaleParamsの部分は空白[[]]でも動作します。その場合は、gdal.Translateが自動で最適なコントラストに設定しますが、多くの場合手動でやるほうが良い結果になります
----> 3 im = Image.open('Masked_' +str(object_name) +'.jpg')
      4 im
      5 

[/usr/local/lib/python3.10/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode, formats)
   3281         warnings.warn(message)
   3282     msg = "cannot identify image file %r" % (filename if filename else fp)
-> 3283     raise UnidentifiedImageError(msg)
   3284 
   3285 

UnidentifiedImageError: cannot identify image file 'Masked_Tokyo_Bay.jpg'

<br><br>
- 下記部分のコードを実行すると真っ白な図が表示されてしまうのが関連しているかとは思います。
```python
nReserve_proj = nReserve_geo.to_crs({'init': epsg})

with rio.open(str(object_name) +'.tiff') as src:
    out_image, out_transform = rio.mask.mask(src, nReserve_proj.geometry,crop=True)
    out_meta = src.meta.copy()
    out_meta.update({"driver": "GTiff",
                 "height": out_image.shape[1],
                 "width": out_image.shape[2],
                 "transform": out_transform})
    
with rio.open('Masked_' +str(object_name) +'.tif', "w", **out_meta) as dest:
    dest.write(out_image)

msk = rio.open(r'Masked_' +str(object_name) +'.tif')
fig, ax = plt.subplots(1, figsize=(18, 18))
show(msk.read([1,2,3]))
plt.show();
```
![image](https://github.com/tamanome/satelliteBook/assets/78333626/a076c6bf-6146-4f05-9f7d-5bd2f6b9d99d)

**Comment by tamanome** [comment]
ご指摘くださりありがとうございます。

該当のセルを以下で置き換えてください。
後ほどノートブックも差し替えます。

```python
gdal.Translate(imgJpg,
               imgTif,
               format='JPEG',
               scaleParams=[[0, 5000, 0, 255]],
               outputType=gdal.GDT_Byte, 
               bandList=[3,2,1])
# scaleParamsの部分は空白[[]]でも動作します。その場合は、gdal.Translateが自動で最適なコントラストに設定しますが、多くの場合手動でやるほうが良い結果になります
im = Image.open('Masked_' +str(object_name) +'.jpg')
im = Image.open('/content/Masked_Tokyo_Bay.jpg')
im
```

直接こちらとは関係がないですが、pystacの動きにもエラーがあるため、そちらも更新します。

**Comment by tamanome** [comment]
ノートブック自体の更新も行いました。

また、白飛び画像ですが、予期せぬエラーというわけではなく、ヒストグラムを見て調整しないと、そのような結果が出てしまうという例で示しています（記載の仕方が分かりづらくてすいません。ノートブックでの説明をやや更新しております）。

**Comment by sukesuke3** [comment]
ご対応いただきありがとうございました。
google colab上で問題なく動作することを確認いたしました。

分かりやすいご説明ありがとうございます。
理解が深まり、衛星データ解析への一歩を踏み出せたような気がします。
（念のため、username、passwordが01_ch3-1DataAccess.ipynbに記載されてしまっておりますが、問題ないでしょうか。）

**Comment by tamanome** [comment]
ご指摘いただきありがとうございます！
うっかり記載したままでした…（対応しました）。

衛星データ解析を踏み出す一歩の一助になれば幸いです。
また引き続きよろしくお願いいたします。
