### ISSUE TITLE
4-4 節の `modisEviTiff._makeMeta` の平均値計算がおかしい

### ISSUE THREAD

**Issue by sankichi92** [tamanome/satelliteBook#7]
https://github.com/tamanome/satelliteBook/blob/00af7d5ed557f4b142aff9ab3099c9b015245066/notebooks/07_ch4-4Agri.ipynb の `modisEviTiff._makeMeta` に「平均値の導出」とコメントされたコードがありますが、平均値ではなく、`self.EVI_list` の最後の要素の画素値を `self.EVI_list` の要素数で割った値を計算していそうです。

`modisEviTiff._makeMeta` のコードは以下です。

```py
  def _makeMeta(self):
    for EVI in self.EVI_list:
      print("OPEN" + EVI)
      # gdal.Openしたデータはosgeo.gdal.Datasetになります。今回はバンドを絞って取得していますが、しなければ複数のバンド情報をもったクラスになります
      data = gdal.Open(EVI, gdalconst.GA_ReadOnly)
      imgs = np.array(data.ReadAsArray()).astype(np.float32) # バンドの情報をnumpy.ndarrayにする
      base_array = self.base_array + imgs # 画像情報の挿入
    
    EVI_ave = base_array/len(self.EVI_list) # 平均値の導出
    # scaledEvi = EVI_ave*0.0001 # スケーリング
    xsize = self.src.RasterXSize # 画像の幅
    ysize = self.src.RasterYSize # 画像の高さ
    return EVI_ave, xsize, ysize
```

平均値の導出は `EVI_ave = base_array/len(self.EVI_list)` で行っています。ローカル変数 `base_array` が `self.EVI_list` から取り出した画素値の合計であれば平均値の計算として正しいですが、`base_array` は繰り返しのたびに上書きされてしまっており、合計にはなっていません。

おそらく、繰り返し中の `base_array = self.base_array + imgs` はインスタンス変数 `self.base_array` と ローカル変数 `base_array` が同一の変数のつもりで書かれているのかと思いますが、実際にはこれらは異なるものです。これは以下のコードで確認できます。

```py
class Foo:
    def __init__(self):
        self.base = 0

    def bar(self):
        base = self.base + 1
        base = self.base + 1
        print(self.base) # 0 (base と self.base が異なるため、self.base の内容は変わらない)
        print(base) # 1 (base と self.base が異なるため、1回目の結果をただ上書きするだけで2回目の結果しか残らない)

foo = Foo()
foo.bar()
```

この平均値計算のバグにより、4-4 節には以下の問題があると思われます。

- `self.EVI_list` の2つの要素のうち後半の要素しか EVI として利用されていない
- EVI が実際の値の半分程度になってしまっている

**Comment by tamanome** [comment]
ご指摘ありがとうございます。
対応しました。ご確認ください。

**Comment by sankichi92** [comment]
ご対応ありがとうございます！
https://github.com/tamanome/satelliteBook/commit/1c32e6e248036da85a664515b9c2bd2e00a57009 で「平均値の導出」コメントの箇所がきちんと平均計算になっていること確認しました。

ただ、細かいですが、平均値計算が for 文の中に入っていて、最後の繰り返し以外の実行が無駄になるのが少し気になりました。

```py
    # 値を入れるための空の配列を準備します
    base_array = np.zeros((pixel,line))

    for EVI in EVI_list:
      print("OPEN" + EVI)
      # gdal.Openしたデータはosgeo.gdal.Datasetになります。今回はバンドを絞って取得していますが、しなければ複数のバンド情報をもったクラスになります
      data = gdal.Open(EVI, gdalconst.GA_ReadOnly)
      imgs = np.array(data.ReadAsArray()).astype(np.float32) # バンドの情報をnumpy.ndarrayにする
      base_array = base_array + imgs # 画像情報の挿入
    
      EVI_avg = base_array/len(EVI_list) # 平均値の導出
      # scaledEvi = EVI_ave*0.0001 # スケーリング
      xsize = src.RasterXSize # 画像の幅
      ysize = src.RasterYSize # 画像の高さ
```

また、指摘の箇所とは無関係ですが、

- 日射量と EVI を重ねたグラフ
- 米の収量と EVI を重ねたグラフ

で EVI の線がなぜか表示されなくなっているようでした。

**Comment by sankichi92** [comment]
> EVI の線がなぜか表示されなくなっている

EVI の平均値計算が修正され、1300〜2000 の値を取っていたものが 2800〜3700 の値を取るようになって、

```py
ax2.set_ylim(1000,2000)
```

で設定されているY軸の範囲外になってしまったためのようです。

**Comment by tamanome** [comment]
重ねてありがとうございます。
インデントが無駄についていますね。
グラフの軸に関しての併せて修正し、再度更新します。

**Comment by tamanome** [comment]
更新いたしました。

**Comment by sankichi92** [comment]
ありがとうございます！

- 平均値計算が for 文の外になっている
- 日射量と EVI、米の収量と EVI それぞれのグラフで EVI が表示される

こと、確認しました。表題の問題解決したのでクローズしますね。

---

余談ですが、EVI の平均値計算は Planetary Computer の STAC API で [MODIS Vegetation Indices 16-Day (250m)](https://planetarycomputer.microsoft.com/dataset/modis-13Q1-061) を検索して、[stackstac](https://stackstac.readthedocs.io/) で時系列の次元をもつ xarray.DataArray を作成して行うと比較的簡単かと思いました。

```py
import pystac_client
import planetary_computer
import stackstac

client = pystac_client.Client.open('https://planetarycomputer.microsoft.com/api/stac/v1', modifier=planetary_computer.sign_inplace)
items = []
for year in range(2007, 2019): # 2007年から2018年までの9月のデータを検索する
  search = client.search(
      collections='modis-13Q1-061',
      datetime=f'{year}-09',
      query=['modis:horizontal-tile=29', 'modis:vertical-tile=5']
  )
  items += search.items()

# stackstac で利用する datetime の値が None なので start_datetime の値で埋める
for item in items:
  item.set_datetime(item.common_metadata.start_datetime)

data_array = stackstac.stack(items, assets=['250m_16_days_EVI'], epsg=32654)
mean_evi = data_array.resample(time='Y').mean().compute() # 年（Y）ごとに EVI の平均を計算する
```

この方法で 4-4 節をやってみたものを https://sankichi92.github.io/satelliteBook/4-4-agri に置いています。ご参考まで。
