### ISSUE TITLE
5章 Sentinel-2のデータ取得部分でエラー

### ISSUE THREAD

**Issue by marina1017** [tamanome/satelliteBook#8]
# 動作環境
Google Colab 09_ch5-1linear.ipynb

# 概要
`intake.open_stac_item_collection()` 関数が`pystac.ItemCollection`を期待しているのに対し、`satstac.ItemCollection` が与えられているため発生しています。

# 解決策
下記のように書き換えると動くことを確認しました

```
catalog = intake.open_stac_item_collection(items) 
```
↓
```
catalog = intake.catalog.Catalog(items)
```
![image](https://user-images.githubusercontent.com/10338059/226524232-cece6102-7c20-4642-b085-497046a36054.png)

# 解決するために見た箇所
https://gis.stackexchange.com/questions/393422/intake-stac-keyerror-open-stac-item-collection

# エラー内容

```
ValueError: Expected <class 'pystac.item_collection.ItemCollection'> instance, got: <class 'satstac.itemcollection.ItemCollection'>
```

![image](https://user-images.githubusercontent.com/10338059/226523982-1813eb60-1a78-4de4-a642-009397dd215d.png)

**Comment by tamanome** [comment]
ありがとうございます。
修正少々お待ちください。

**Comment by tamanome** [comment]
`intake`を利用していた箇所を修正しました。Sentinel-2のデータは正しくダウンロードされるようになっております。ご確認ください。

**Comment by marina1017** [comment]
ご確認頂きありがとうございました
